# Generated by Django 5.0.6 on 2024-06-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gptConservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='create_date',
            field=models.IntegerField(),
        ),
    ]
